version: "3.8"

services:
  db:
    image: postgres:14.2
    container_name: crawler_db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=crawler_dev
    ports:
      - "5432:5432"
